### ISSUE TITLE
[Bug]: Internal Ids and Syncing

### ISSUE THREAD

**Issue by TylerBloom** [MonarchDevelopment/SquireCore#11]
Most of the client-server tournament sync protocol is done. However, there is still one rather large issue remaining. Say client A registers a new player locally, and syncs this with the server (and other clients). This works perfectly fine until they try to use that player's `PlayerId` in a tournament operation. All `Uuid`s are randomly generated locally. This means that all tournament operations that get stored and synced need to use the non-id varients of their identifiers. I don't believe there is a way to ensure this at the type level, so this should be clearly documented in the `TournamentManager`.

**Comment by TylerBloom** [comment]
This is partially being addressed in #17. There, a player's id will be their account id. This does not remove the issue for players that are guests or for rounds. I think instead of trying to retroactively change ids used in operations, we should have a method of syncing ids.

**Comment by TylerBloom** [comment]
Thinking about this more, `Uuid`s can be constructed from a `u128`, which can be created by a hasher. For guest players, the player's name can be hashed to create the `u128`. This should be "random" enough.

Doing this for matches will be more difficult as the hash can't be tied to relative `TournOp` ordering nor can it be temporally determined (e.g what time the match was created). The list of players is the best bet, but that isn't good enough. If two matches have the same list of players, they would have the same ID. Instead, we could hash the hash of the list of players (and so on) to get a new ID.

This plan relies on having a `Hasher` that is deterministic and functions identically across basically all platforms (Linux to Windows to WASM).

**Comment by djpiper28** [comment]
ids should ideally remain random to make them friendly for development. synchronisation should look at matching operations based off parameters not ids probably.

**Comment by TylerBloom** [comment]
@djpiper28, IDs need to be somewhat deterministic. If I have a list of tournament operations and I construct two tournaments out of that list, they need to always be identical. This includes ID generation. Otherwise, we will not have a consistent way of syncing and recreating tournaments.

For example, say "PlayerA" registers for a tournament and has an ID that is `0x1`. That player then registers a deck. The tournament operation needs to be able to refer to that player, so we will use their ID. So, we have an operation for adding a deck that takes their ID (`0x1`), deck name, and deck. Now, I sync with something, like the SC server. In their tournament, they register "PlayerA" and generate their ID, say `0x2`. They then try to add their deck, and the operation fails because no player in their tournament has the ID `0x1`. You could always refer to the player by name, but you can't do that with matches. Match numbers are determined relatively.

**Comment by TylerBloom** [comment]
[This hasher](https://docs.rs/fasthash/latest/fasthash/xx/struct.Hasher64.html) looks promising for this feature. The crate also includes other hashing algorithms that can be used to tone the library for performance. The default hasher in the Rust standard library is comparatively slow to many algorithms because it protects against HashDoS attacks. This is not really an issue for the tournament library.

**Comment by TylerBloom** [comment]
Giving this yet more thought, every operation can be timestamped. Since `chrono` timestamps are measured to the nanosecond, it is extremely unlikely that two timestamps from different systems will be the same. This can be used a form of "salt" for creating `Uuid`s. The timestamp hash can form the top 64 bits, and the bottom 64 can be formed by the hash of the data (player name, players in match, etc).

This combined with a cross-platform deterministic hasher should solve this problem. Operations should then be limited to the IDs and the tournament should expose `get_player_id` and `get_match_id` methods.

**Comment by djpiper28** [comment]
giving this some thought, that does sound reasonable

**Comment by TylerBloom** [comment]
The changes discussed here should be implemented, so I'm closing this issue.
