### ISSUE TITLE
[Dev]: Basic Squire Account

### ISSUE THREAD

**Issue by TylerBloom** [MonarchDevelopment/SquireCore#14]
The first step in getting Squire accounts set up will be making the account structs. These should go in `squire_lib` as we will being using them in the tournament model in order to register players, judges, and admins.

For users, their struct should contain identifying information such as their display name, user name, and `Uuid` as well as their privacy/sharing information. Notably, authentication material such as a password should **not** be in the struct.

For organizations, similar identifying information is needed as well as the owner, default judge and admin accounts, and default tournament settings. Eventually, this should also be (optionally) linked to a discord server.

**Comment by TheDeveloper101** [comment]
went ahead and submitted a pr. i didnt add anything about a discord account yet because a) idk how and b) its not a feature that will be added immediately

**Comment by TylerBloom** [comment]
Ya, that's completely fine. We can move that much into a separate issue. That will require modeling some basic Discord info in `squire_lib`.
