### ISSUE TITLE
[Bug]: (FFI) Changing minimum and, maximum deck count can cause errors

### ISSUE THREAD

**Issue by djpiper28** [MonarchDevelopment/SquireCore#41]
## What went wrong:

When changing the min and, max deck count via `tid_update_settings` such that new_min > old_max, whilst making sure the new values are valid the method fails.

## Expected behavior:

The method should not fail as, the new values would be valid.

## Fix
When `new_min >= old_max` swap the order of apply setMin and, setMax

**Comment by TylerBloom** [comment]
Is the bounds check for equality between old max and new min required? Currently, the check is `new_min > old_max`.

**Comment by djpiper28** [comment]
> Is the bounds check for equality between old max and new min required? Currently, the check is `new_min > old_max`.

I believe you might be right after double checking. However in FFI is this done atomically?

**Comment by djpiper28** [comment]
after cargo clean and, stuff the tests I wrote for it are passing, I image that it cached something somewhere poorly
