### ISSUE TITLE
[Bug]: Invoking cargo run from SquireCore instead of squire_core causes a runtime error.

### ISSUE THREAD

**Issue by wrobins6** [MonarchDevelopment/SquireCore#72]
## What went wrong:
When opening the server in a browser after attempting to run the backend from the main ```SquireCore``` directory, the following runtime error occurs: 

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', squire_core/src/assets.rs:10:14
```

## Expected behavior:
The backend server should be able to be run from anywhere.

## To Reproduce:
Invoke ```cargo run``` from the main ```SquireCore``` directory instead of ```squire_core```, and open the server in your web browser.

**Comment by TylerBloom** [comment]
This should be a fairly easy problem to fix. The backend code for storing and retrieving static assets (like the frontend resources) is in `squire_core/src/assets.rs`. The functions that retrieve this data use the executable's caller's location to find the `assets/` directory (which is stored at the root of the repo). Instead, we should use paths relative to the backend's sub-directory. We already do this in the backend's `build.rs` file to find the `squire_web` subdirectory. We should do the same thing in the `assets.rs`.

**Comment by wrobins6** [comment]
I have corrected the ```use``` statement in ```assets.rs``` in my most recent commit. Should I close this issue?

**Comment by TylerBloom** [comment]
You said that there were still issues if ran the backend from other locations in the repo, ya? Did you try using the `env!` macro over `env::var`?

**Comment by wrobins6** [comment]
I was referring to our testing of ```env::var("CARGO_MANIFEST_DIR")``` in conjunction with ```unwrap()``` in various files. I was trying to invoke it at runtime with ```unwrap()``` to see what it returned, and it caused a crash. From what we read, it seems like ```CARGO_MANIFEST_DIR``` is only available at compile time, which would explain that. This was a separate, uncommitted experiment from the fix itself, and the backend should work from other locations. I could also try to implement the fix using env! if you want though.

**Comment by TylerBloom** [comment]
Ah, I must have misunderstood, then. If you can correctly run the backend from anywhere, then I'm happy.

**Comment by wrobins6** [comment]
To clarify, it does not run from the ```squire_lib```, ```squire_sdk```, ```squire_tests``` directories, but there is no runtime error of any kind. Cargo itself throws an error:

```error: a bin target must be available for cargo run```

Is this due to their configurations? The other folders within the project work fine.
