### ISSUE TITLE
[Dev]: Sorted Player and Rounds

### ISSUE THREAD

**Issue by TylerBloom** [MonarchDevelopment/SquireCore#80]
## Unmet Need:
Currently, players and rounds are not sorted anywhere in the UI. They need to be sorted in the player and round scroll as well as in the rounds in the selected player view.

## Solution:
Rust has a crate, `Itertools`, that should be of great use here.

**Comment by wrobins6** [comment]
In what way would you like them to be sorted?

**Comment by TylerBloom** [comment]
Players should be sorted by status and then alphabetically. Rounds should be sorted by status then round number in descending order
